### ISSUE TITLE
Add 2nd level of authentication for all the logins

### ISSUE THREAD

**Issue by ctspukar** [ctspukar/Insurance-Agent-System#2]
Same as in back end admin panel. We would like to add 2nd level authentication for members, group and brokers. Currently, the verification code is sent to email however we will also need to see option to send the code to mobile device.

**Comment by halostream** [comment]
user tested site and is not getting verification email with code to enter they have tried a couple of times and have alos checked spam but no email

**Comment by ctspukar** [comment]
I tested it today at silverbackadmin and got the verification code in my SPAM FOLDER. 
![image](https://user-images.githubusercontent.com/20727591/28690071-dc9e21fe-72e5-11e7-84c4-b3fde0e54ee3.png)

**Comment by ctspukar** [comment]
Make direct changes to https://brokerexchanges.com/ for this release.
